### ISSUE TITLE
Facing error when trying to run given example of the DRNN-rec-DEC combination on the CBF dataset

### ISSUE THREAD

**Issue by Ashutosh-Saxena** [blafabregue/TimeSeriesDeepClustering#1]
During running the given example - 
python ucr_experiments.py --dataset CBF --itr 1 --architecture dilated_cnn --encoder_loss reconstruction --clustering_loss DEC --archives UCRArchive_2018 --hyper default_hyperparameters.json

I am getting this error:

KeyError: 'The optimizer cannot recognize variable clustering/clustering:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'

Can anyone explain why I am getting this error and guide me how it can be fixed?

**Comment by blafabregue** [comment]
Hello,
The problem should be fixed now, just pull the last commit. My code was in tf 2.3, now it is tf t.15+ so it seems that some behaviors have changed. I had to switch all "tf.keras.optimizers.Adam" to "tf.keras.optimizers.legacy.Adam". 
Hope it works for you.
