### ISSUE TITLE
Changing number of epochs at training

### ISSUE THREAD

**Issue by gmkim97** [blafabregue/TimeSeriesDeepClustering#2]
Hello! Thank you for this repository and your paper. I recently started to study about Deep Clustering with the paper.
Here, I have a question : 

I want to train with your example, DRNN-rec-DEC combination on the CBF dataset, but it keeps training for 4 epochs. 
How can I change the number of epochs at the training?

**Comment by blafabregue** [comment]
Hello!
Thank you for your interest in my work. To change the number of epochs, you must change the "nb_steps" parameter in the file default_hyperparameters.json. However, note that it is the number of batches and not the number of epochs, so you need to set it to "<nb_epochs>*<dataset_size>/<batch_size>".

**Comment by gmkim97** [comment]
With your stated relationship, Modifying "nb_steps" changes number of epochs normally.
Thank you for your kind help, again. Have a nice day.
